curl -X GET http://localhost:8083/greeting
curl -X GET http://localhost:8083/greeting
curl -X GET http://localhost:8083/greeting
curl -X GET http://localhost:8083/greeting
curl -X GET http://localhost:8083/greeting
curl -X GET http://localhost:8083/greeting
curl -X GET http://localhost:8083/greeting
curl -X GET http://localhost:8083/greeting
curl -X GET http://localhost:8083/greeting