curl -X GET http://localhost:8082/api
curl -X GET http://localhost:8082/api
curl -X GET http://localhost:8082/api
curl -X GET http://localhost:8082/api
curl -X GET http://localhost:8082/api
curl -X GET http://localhost:8082/api
curl -X GET http://localhost:8082/api
curl -X GET http://localhost:8082/api/dotnet
curl -X GET http://localhost:8082/api/dotnet
curl -X GET http://localhost:8082/api/dotnet
curl -X GET http://localhost:8082/api/dotnet
curl -X GET http://localhost:8082/api/dotnet
curl -X GET http://localhost:8082/api/dotnet
