service: python-flask-api

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.8
  stage: datadogpoweruser

functions:
  api:
    handler: wsgi_handler.handler
    name: python-flask-api
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /hello
          method: ANY
      - http:
          path: /erro
          method: ANY
          
plugins:
  - serverless-wsgi
  - serverless-python-requirements
